### ISSUE TITLE
Icons broken on iOS 

### ISSUE THREAD

**Issue by hessius** [nolimits4web/Framework7-Icons#2]
Some icons are broken on iOS. Specifically this seems to affect some outline icons. I'm using iOS 10.1.1
Attaching screenshots of the ones I've spotted
![img_1034](https://cloud.githubusercontent.com/assets/1499030/20981716/0c569c96-bcb6-11e6-9ca8-4abe038be936.PNG)
![img_1035](https://cloud.githubusercontent.com/assets/1499030/20981723/0d142266-bcb6-11e6-95fc-2351b37df8f9.PNG)
![img_1036](https://cloud.githubusercontent.com/assets/1499030/20981721/0cf46070-bcb6-11e6-9c1f-e8a314cb5dcf.PNG)
![img_1037](https://cloud.githubusercontent.com/assets/1499030/20981720/0cdcdd24-bcb6-11e6-9c1e-d65a752727e7.PNG)
![img_1038](https://cloud.githubusercontent.com/assets/1499030/20981719/0cc15eb4-bcb6-11e6-890c-97199bee3168.PNG)
![img_1039](https://cloud.githubusercontent.com/assets/1499030/20981722/0cfd22c8-bcb6-11e6-80a7-a6b8f9237769.PNG)
![img_1040](https://cloud.githubusercontent.com/assets/1499030/20981724/0d236762-bcb6-11e6-9ca0-0e9a959cbfc1.PNG)
![img_1041](https://cloud.githubusercontent.com/assets/1499030/20981726/0d32c004-bcb6-11e6-8f57-200806b6286e.PNG)
![img_1042](https://cloud.githubusercontent.com/assets/1499030/20981725/0d3019ee-bcb6-11e6-9681-0f335c24e064.PNG)
![img_1043](https://cloud.githubusercontent.com/assets/1499030/20981728/0d5e3c02-bcb6-11e6-9db7-929a75a69c0d.PNG)

**Comment by nolimits4web** [comment]
Yeah, there are some issues with some icons on iOS only. Will redraw broken icons

**Comment by dawiinci** [comment]
I can confirm this issue on iOS. I was looking for a bug in my own code first...

Thanks for fixing it soon.

**Comment by nolimits4web** [comment]
Fixed now in 0.8.9 release
